env:
  browser: true
  commonjs: true
  es2021: true
  node: true
extends: standard-with-typescript
parserOptions:
  project: tsconfig.json
  ecmaVersion: latest
rules:
  {
    'semi': 'off',
    '@typescript-eslint/semi': 'off',
    'space-before-function-paren': 'off',
    '@typescript-eslint/space-before-function-paren': 'off',
    'comma-dangle': 'off',
    '@typescript-eslint/comma-dangle': 'off',
  }
