export enum FTP {
  RestartMarkerReplay = 110,
  ServiceReadyInNnnMinutes = 120,
  DataConnectionAlreadyOpenTransferStarting = 125,
  FileStatusOkayAboutToOpenDataConnection = 150,

  CommandNotImplementedSuperfluous = 202,
  SystemStatus = 211,
  DirectoryStatus = 212,
  FileStatus = 213,
  HelpMessage = 214,
  NameSystemType = 215,
  ServiceReadyForNewUser = 220,
  ServiceClosingControlConnection = 221,
  DataConnectionOpenNoTransferInProgress = 225,
  ClosingDataConnectionRequestedFileActionSuccess = 226,
  EnteringPassiveMode = 227,
  EnteringLongPassiveMode = 228,
  EnteringExtendedPassiveMode = 229,
  UserLoggedInProceed = 230,
  UserLoggedOutServiceTerminated = 231,
  LogoutCommandNotedWillCompleteWhenTransferDone = 232,

  // A higher level nonstandard code created by Microsoft.
  AuthenticationMechanismAccepted = 234,
  RequestedFileActionOkayCompleted = 250,
  PathnameCreated = 257,

  UserNameOkayNeedPassword = 331,
  NeedAccountForLogin = 332,
  RequestedFileActionPendingFurtherInformation = 350,

  ServiceNotAvailableClosingControlConnection = 421,
  CannotOpenDataConnection = 425,
  ConnectionClosedTransferAborted = 426,
  InvalidUsernameOrPassword = 430,
  RequestedHostUnavailable = 434,
  RequestedFileActionNotTaken = 450,
  RequestedActionAbortedLocalErrorInProcessing = 451,
  RequestedActionNotTakenInsufficientStorage = 452,

  SyntaxErrorCommandUnrecognizedCommandLineTooLong = 500,
  SyntaxErrorInParametersOrArguments = 501,
  CommandNotImplemented = 502,
  BadSequenceOfCommands = 503,
  CommandNotImplementedForThatParameter = 504,
  NotLoggedIn = 530,
  NeedAccountForStoringFiles = 532,
  CouldNotConnectToServerPolicyRequiresSsl = 534,
  RequestedActionNotTakenFileUnavailable = 550,
  RequestedActionAbortedPageTypeUnknown = 551,
  RequestedFileActionAbortedExceededStorageAllocation = 552,
  RequestedActionNotTakenFileNameNotAllowed = 553,

  IntegrityProtectedReply = 631,
  ConfidentialityAndIntegrityProtectedReply = 632,
  ConfidentialityProtectedReply = 633,

  ConnectionResetByPeerForciblyClosedByRemoteHost = 10054,
  CannotConnectToRemoteServer = 10060,
  CannotConnectToRemoteServerActivelyRefusedByServer = 10061,
  DirectoryNotEmpty = 10066,
  TooManyUsersServerIsFull = 10068,
}
