// https://support.microsoft.com/en-us/help/943891/the-http-status-code-in-iis-7-0-iis-7-5-and-iis-8-0

import { mergeEnums } from './helpers';
import { Http } from './http';

export enum IIS {
  Continue = 100,
  SwitchingProtocols = 101,

  OK = 200,
  Created = 201,
  Accepted = 202,
  NonauthoritativeInformation = 203,
  NoContent = 204,
  ResetContent = 205,
  PartialContent = 206,

  MovedPermanently = 301,
  ObjectMoved = 302,
  NotModified = 304,
  TemporaryRedirect = 307,

  BadRequest = 400,
  InvalidDestinationHeader = 400.1,
  InvalidDepthHeader = 400.2,
  InvalidIfHeader = 400.3,
  InvalidOverwriteHeader = 400.4,
  InvalidTranslateHeader = 400.5,
  InvalidRequestBody = 400.6,
  InvalidContentLength = 400.7,
  InvalidTimeout = 400.8,
  InvalidLockToken = 400.9,

  AccessDenied = 401,
  LogonFailed = 401.1,
  LogonFailedDueToServerConfiguration = 401.2,
  UnauthorizedDueToACL = 401.3,
  AuthorizationFailedByFilter = 401.4,
  AuthorizationFailedByISAPI_CGI = 401.5,
  AccessDeniedTooManyRequestsFromClientIP_DynamicIPRestrictionConcurrentRequestRateLimitReached = 401.501,
  ForbiddenTooManyRequestsFromSameIP_DynamicIPRestriction = 401.502,
  AccessDeniedIPAddressRestriction = 401.503,
  AccessDeniedHostnameRestriction = 401.503,

  Forbidden = 403,
  ExecuteAccessForbidden = 403.1,
  ReadAccessForbidden = 403.2,
  WriteAccessForbidden = 403.3,
  SSLRequired = 403.4,
  SSL128Required = 403.5,
  IPAddressRejected = 403.6,
  ClientCertificateRequired = 403.7,
  SiteAccessDenied = 403.8,
  ForbiddenTooManyClientsAreTryingToConnectToTheWebServer = 403.9,
  ForbiddenWebServerIsConfiguredToDenyExecuteAccess = 403.1,
  ForbiddenPasswordHasBeenChanged = 403.11,
  MapperDeniedAccess = 403.12,
  ClientCertificateRevoked = 403.13,
  DirectoryListingDenied = 403.14,
  ForbiddenClientAccessLicensesHaveExceededLimitsOnTheWebServer = 403.15,
  ClientCertificateIsUntrustedOrInvalid = 403.16,
  ClientCertificateHasExpiredOrIsNotYetValid = 403.17,
  CannotExecuteRequestedURLInTheCurrentApplicationPool = 403.18,
  CannotExecuteCGIApplicationsForTheClientInThisApplicationPool = 403.19,
  PassportLogonFailed = 403.2,
  SourceAccessDenied = 403.21,
  InfiniteDepthIsDenied = 403.22,
  ForbiddenTooManyRequestsFromClientIP_DynamicIPRestrictionConcurrentRequestRateLimitReached = 403.501,
  ForbiddenTooManyRequestsFromClientIP_DynamicIPRestrictionMaximumRequestRateLimitReached = 403.502,
  ForbiddenIPAddressIncludedInTheDenyListOfIPRestriction = 403.503,
  ForbiddenHostNameIncludedInTheDenyListOfIPRestriction = 403.504,

  NotFound = 404,
  Notfound = 404.0,
  SiteNotFound = 404.1,
  ISAPIOrCGIRestriction = 404.2,
  MIMETypeRestriction = 404.3,
  NoHandlerConfigured = 404.4,
  DeniedByRequestFilteringConfiguration = 404.5,
  VerbDenied = 404.6,
  FileExtensionDenied = 404.7,
  HiddenNamespace = 404.8,
  FileAttributeHidden = 404.9,
  RequestHeaderTooLong = 404.1,
  RequestContainsDoubleEscapeSequence = 404.11,
  RequestContainsHighBitCharacters = 404.12,
  ContentLengthTooLarge = 404.13,
  RequestURLTooLong = 404.14,
  QueryStringTooLong = 404.15,
  DAVRequestSentToTheStaticFileHandler = 404.16,
  DynamicContentMappedToTheStaticFileHandlerViaAWildcardMIMEMapping = 404.17,
  QuerystringSequenceDenied = 404.18,
  DeniedByFilteringRule = 404.19,
  TooManyURLSegment = 404.2,
  NotFoundTooManyRequestsFromTheSameClientIP_DynamicIPRestrictionConcurrentRequestRateLimitReached = 404.501,
  NotFoundTooManyRequestsFromTheSameClientIP_DynamicIPRestrictionMaximumRequestRateLimitReached = 404.502,
  NotFoundTheIPAddressIsIncludedInTheDenyListOfIPRestriction = 404.503,
  NotFoundTheHostNameIsIncludedInTheDenyListOfIPRestriction = 404.504,

  MethodNotAllowed = 405,
  ClientBrowserDoesNotAcceptTheMIMETypeOfTheRequestedPage = 406,
  RequestTimedOut = 408,
  PreconditionFailed = 412,

  InternalServerError = 500,
  ModuleOrISAPIErrorOccurred = 500.0,
  ApplicationIsShuttingDownOnTheWebServer = 500.11,
  ApplicationIsBusyRestartingOnTheWebServer = 500.12,
  WebServerIsTooBusy = 500.13,
  DirectRequestsForGlobalAsaxAreNotAllowed = 500.15,
  ConfigurationDataIsInvalid = 500.19,
  ModuleNotRecognized = 500.21,
  AnASPNETHttpModulesConfigurationDoesNotApplyInManagedPipelineMode = 500.22,
  AnASPNETHttpHandlersConfigurationDoesNotApplyInManagedPipelineMode = 500.23,
  AnASPNETImpersonationConfigurationDoesNotApplyInManagedPipelineMode = 500.24,
  RewriteErrorDuringRQ_BEGIN_REQUESTNotificationHandling = 500.5,
  RewriteErrorDuringGL_PRE_BEGIN_REQUESTNotificationHandling = 500.51,
  RewriteErrorDuringRQ_SEND_RESPONSENotificationHandling = 500.52,
  RewriteErrorDuringRQ_RELEASE_REQUEST_STATENotificationHandling = 500.53,
  InternalASPError = 500.1,

  HeaderValuesSpecifyUnimplementedConfiguration = 501,
  InvalidGatewayOrProxyResponse = 502,

  CGIApplicationTimeout = 502.1,
  BadGatewayPrematureExit = 502.2,
  BadGatewayForwarderConnectionErrorARR = 502.3,
  BadGatewayNoServerARR = 502.4,

  ServiceUnavailable = 503,
  ApplicationPoolUnavailable = 503.0,
  ConcurrentRequestLimitExceeded = 503.2,
  ASPNETQueueFull = 503.3,
  FastCGIQueueFull = 503.4,
}

export const IISHttp = mergeEnums(Http, IIS);
