// https://developer.twitter.com/en/support/twitter-api/error-troubleshooting

export enum TwitterHttp {
  Ok = 200,
  NotModified = 304,
  BadRequest = 400,
  Unauthorized = 401,
  Forbidden = 403,
  NotFound = 404,
  NotAcceptable = 406,
  Gone = 410,
  EnhanceYourCalm = 420,
  UnprocessableEntity = 422,
  TooManyRequests = 429,
  InternalServerError = 500,
  BadGateway = 502,
  ServiceUnavailable = 503,
  GatewayTimeout = 504,
}

export enum TwitterErrors {
  InvalidCoordinates = 3,
  NoIpLocationAssociation = 13,
  NoUserTermsMatch = 17,
  AuthenticationFailure = 32,
  PageDoesNotExist = 34,
  CannotSelfReportForSpam = 36,
  ParameterMissing = 38,
  AttachmentUrlParameterInvalid = 44,
  UserNotFound = 50,
  UserSuspended = 63,
  AccountSuspended = 64,
  TwitterAPIv1Inactive = 68,
  ClientActionNotPermitted = 87,
  RateLimitExceeded = 88,
  InvalidOrExpiredToken = 89,
  SslRequired = 92,
  DirectMessageAccessDenied = 93,
  CredentialVerificationFailure = 99,
  SpecifiedUserNotFoundInList = 109,
  UserToRemoveNotAListMember = 110,
  AccountUpdateFailed = 120,
  OverCapacity = 130,
  InternalError = 131,
  CouldNotAuthenticate = 135,
  AlreadyFavorited = 139,
  NoStatusFound = 144,
  UserMessageSendFailure = 150,
  MessageSendError = 151,
  DuplicateFollowRequest = 160,
  FollowLimitExceeded = 161,
  UnauthorizedStatusRequest = 179,
  DailyUpdateLimitExceeded = 185,
  TweetTextOverLimit = 186,
  DuplicateStatus = 187,
  MissingOrInvalidUrlParameter = 195,
  SpamReportLimitExceeded = 205,
  OwnerMustAllowDMsFromAnyone = 214,
  BadAuthenticationData = 215,
  UnauthorizedResourceCredentials = 220,
  PossibleAutomatedRequest = 226,
  /**
   * Possibly deprecated
   */
  UserMustVerifyLogin = 231,
  EndpointRetired = 251,
  CannotPerformWriteActions = 261,
  SelfMuteNotAllowed = 271,
  NotMutingSpecifiedUser = 272,
  SingleAnimatedGifAllowed = 323,
  MediaIdsValidationFailure = 324,
  MediaIdNotFound = 325,
  AccountTemporarilyLocked = 326,
  AlreadyRetweeted = 327,
  YouCannotSendMessagesToUser = 349,
  DirectMessageCharacterLimitExceeded = 354,
  SubscriptionAlreadyExists = 355,
  ReplyToUnavailableTweet = 385,
  AttachmentTypeLimitExceeded = 386,
  UrlInvalid = 407,
  CallbackUrlNotApproved = 415,
  InvalidSuspendedApplication = 416,
  OobOnlyOauthSupport = 417,
  TweetNoLongerAvailable = 421,
  TweetUnavailableForRuleViolations = 422,
  SomeTweetActionsDisabledByTwitter = 425,
  TweetAuthorRestrictedReplies = 433,
}

export enum TwitterWebhookErrors {
  CouldNotAuthenticate = 32,
  Forbidden = 200,
  WebhookURIDoesNotMeetRequirements = 214,
  HighLatency = 214,
  TooManyResourcesAlreadyCreated = 214,
  AppCannotPerformWriteAccess = 261,
}
