name: Check for TypeScript build errors

on:
  push:
    branches: [master, develop]

  pull_request:
    branches: [master, develop]
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review

jobs:
  run-tsc:
    timeout-minutes: 3
    runs-on: ubuntu-latest
    if: ${{ !github.event.pull_request.draft }}
    steps:
      - name: Github checkout
        uses: actions/checkout@v5
      - name: Setup nodejs
        uses: actions/setup-node@v4
        with:
          node-version: latest
          cache: 'npm'

      - name: Install dependencies
        run: npm ci --ignore-scripts
      - name: Run tsc
        run: npm run compile --noEmit --noErrorTruncation
